HOMEPAGE = "https://www.lounaat.info/"
BROWSER = "Chrome"
ID_CONTENT = "//*[@id=\"content\"]/div/div[1]/div/div/section[2]/div/div/div[1]/div/div/div[9]"
PATH_FILE_TO_WRITE = "${CURDIR}/../file_resources/menus_list.txt"
ID_BUTTON_COOKIES = "//body/div[@id='qc-cmp2-container']/div[@id='qc-cmp2-main']/div[1]/div[1]/div[2]/div[1]/button[3]"
ID_TEXT_INPUT_ELEMENT = "//body/div[2]/div[2]/div[2]/div[1]/form[1]/input[1]"
ID_BUTTON_SEARCH = "//button[contains(text(),'Hae')]"
ID_BUTTON_OPEN_SEARCH = "//body/div[2]/div[2]/div[3]/div[1]/a[1]"
ID_TEXT_MENU= "//body/div[6]/div[1]/div[2]"
