HOMEPAGE = "https://www.lounaat.info/"
# BROWSER = "Headlesschrome"
BROWSER = "chrome"
PATH_FILE_TO_WRITE = "${CURDIR}/../file_resources/menus_list.txt"
ID_BUTTON_COOKIES = "//*[@id='qc-cmp2-ui']/div[2]/div/button[3]"
ID_BUTTON_AD = "//div[@class='banner-close']"
ID_BUTTON_SUBMENU = "//i[@class='fa fa-bars']"
ID_TEXT_INPUT_ELEMENT = "//div[@class='form-container']//input[@data-lounaat-element='query']"
ID_BUTTON_SEARCH = "//button[contains(text(),'Hae')]"
ID_BUTTON_OPEN_SEARCH = "//*[@id='navi']/a[1]"
ID_TEXT_MENU= "//div[@class='item-body']"
